esphome:
    name: ${device_name}
    friendly_name: ${friendly_name}
    on_boot:
        priority: -10
        then:
            # Enable external antenna by default
            - output.turn_off: ant_gpio3    # LOW
            - output.turn_on:  ant_gpio14   # HIGH → external antenna

esp32:
    variant: esp32c6
    board: seeed_xiao_esp32c6
    framework:
        type: esp-idf
        version: recommended
        sdkconfig_options:
            # Enable Bluetooth and NimBLE, disable Bluedroid
            CONFIG_BT_ENABLED: "y"
            CONFIG_BT_BLUEDROID_ENABLED: "n"
            CONFIG_BT_NIMBLE_ENABLED: "y"

            # Roles (peripheral/broadcaster sufficient)
            CONFIG_BT_NIMBLE_ROLE_PERIPHERAL: "y"
            CONFIG_BT_NIMBLE_ROLE_BROADCASTER: "y"
            CONFIG_BT_NIMBLE_ROLE_CENTRAL: "n"
            CONFIG_BT_NIMBLE_ROLE_OBSERVER: "n"

            # Security (bonding + LESC)
            CONFIG_BT_NIMBLE_SECURITY_ENABLE: "y"
            CONFIG_BT_NIMBLE_SM_LEGACY: "y"
            CONFIG_BT_NIMBLE_SM_SC: "y"

# IMPORTANT: Do NOT include esp32_ble:, esp32_ble_tracker:, or bluetooth_proxy: here.
# The irk_capture component fully initializes and manages NimBLE itself.

logger:
    level: DEBUG
    baud_rate: 115200
    hardware_uart: USB_CDC

api:
    encryption:
        key: ${api_key}
    reboot_timeout: 15min

ota:
    - platform: esphome
      password: ${ota_password}
      version: 2

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    domain: .local
    use_address: ${device_name}.local
    power_save_mode: NONE
    fast_connect: true
    enable_on_boot: true
    reboot_timeout: 10min
    ap:
        ssid: "${friendly_name} Fallback"
        password: !secret wifi_captive
        ap_timeout: 120s

captive_portal:

mdns:

# Status LED (use whichever pin matches your hardware; GPIO10 or GPIO15 are common on the XIAO C6)
status_led:
    pin:
        number: GPIO10
        inverted: true

# External antenna control (GPIO3, GPIO14)
output:
    - platform: gpio
      id: ant_gpio3
      pin: GPIO3

    - platform: gpio
      id: ant_gpio14
      pin: GPIO14

# Pull your irk_capture external component (must contain ESP-IDF NimBLE code)
external_components:
    - source:
        type: git
        url: https://github.com/DerekSeaman/irk-capture
        ref: main
      components: [irk_capture]
      refresh: 0s

# Configure the custom component
irk_capture:
    id: irk
    ble_name: "IRK Capture"
    start_on_boot: true

# Expose text sensors for captured IRK and identity address
text_sensor:
    - platform: irk_capture
      irk_capture_id: irk
      last_irk:
          id: last_irk
          name: "IRK"
      last_address:
          id: last_addr
          name: "Device MAC"

# BLE advertising on/off (drives start/stop advertising)
switch:
    - platform: irk_capture
      irk_capture_id: irk
      advertising:
          id: ble_advertising
          name: "BLE Advertising"
          restore_mode: ALWAYS_OFF

    # External antenna selector
    - platform: template
      name: "External Antenna"
      optimistic: true
      restore_mode: ALWAYS_ON
      turn_on_action:
          - output.turn_off: ant_gpio3   # LOW
          - output.turn_on:  ant_gpio14  # HIGH → external antenna
      turn_off_action:
          - output.turn_off: ant_gpio3   # LOW
          - output.turn_off: ant_gpio14  # LOW → internal antenna

# Buttons
button:
    - platform: irk_capture
      irk_capture_id: irk
      new_mac:
          id: new_mac_btn
          name: "Generate New MAC"
    - platform: restart
      name: "Restart Device"

# Text input to change the BLE name dynamically
text:
    - platform: irk_capture
      irk_capture_id: irk
      ble_name:
          id: ble_name_input
          name: "BLE Device Name"
          mode: text

# Diagnostics and basics
sensor:
    - platform: uptime
      name: "Uptime"
      unit_of_measurement: "h"
      accuracy_decimals: 2
      update_interval: 60s
      filters:
          - lambda: return x / 3600.0;

    - platform: internal_temperature
      name: "Internal Temp"
      entity_category: diagnostic

    - platform: wifi_signal
      name: "Wi-Fi Signal"
      update_interval: 30s
      entity_category: diagnostic

time:
    - platform: sntp
      id: sntp_time
      servers:
          - 0.pool.ntp.org
          - 1.pool.ntp.org
