esp32:
  variant: esp32c6
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_SOC_WIFI_HE_SUPPORT: y   # Future Wi-Fi 6 Support
      CONFIG_ESP_WIFI_11AX_SUPPORT: y # Future Wi-Fi 6 Support

esphome:
  on_boot:
    priority: -10
    then:
      - output.turn_off: ant_gpio3 # Enables external antenna
      - output.turn_on: ant_gpio14 # Enables external antenna

logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG

# Status LED behavior: Solid = all OK, slow blink = Wi-Fi but no API client, fast blink = no Wi-Fi
status_led:
  pin:
    number: GPIO15

api:
  encryption:
    key: ${api_key}
  reboot_timeout: 15min

ota:
  - platform: esphome
    password: ${ota_password}
    version: 2

wifi:
  domain: .local
  use_address: ${device_name}.local
  fast_connect: true
  enable_on_boot: true
  reboot_timeout: 10min
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_captive
    ap_timeout: 120s

captive_portal:

mdns:
  disabled: false

esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 211ms
    window: 180ms
    continuous: true

bluetooth_proxy:
  active: true

sensor:
  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "h"
    accuracy_decimals: 2
    update_interval: 60s
    filters:
      - lambda: return x / 3600.0;  # Convert seconds to hours

  - platform: internal_temperature
    name: "Internal Temp"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "Wi-Fi Signal"
    update_interval: 30s
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    bssid:
      name: "BSSID"
      entity_category: diagnostic
    ip_address:
      name: "IP"
      entity_category: diagnostic

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org

switch:
  - platform: template
    name: "External Antenna"
    optimistic: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      - output.turn_off: ant_gpio3   # LOW
      - output.turn_on: ant_gpio14  # HIGH → external antenna
    turn_off_action:
      - output.turn_off: ant_gpio3  # LOW
      - output.turn_off: ant_gpio14 # LOW → internal antenna

# Antenna control pins
output:
  - platform: gpio
    pin: GPIO3
    id: ant_gpio3

  - platform: gpio
    pin: GPIO14
    id: ant_gpio14
